export const layoutStyles = {
  adminLayout: "flex min-h-screen bg-surface",
  mobileBackdrop: "fixed inset-0 z-40 bg-on-surface/20 backdrop-blur-sm lg:hidden",
  adminSidebar: "fixed inset-y-0 left-0 z-50 w-72 bg-primary text-on-primary transition-transform duration-300 ease-in-out lg:static lg:translate-x-0",
  sidebarContent: "flex h-full flex-col p-6",
  sidebarHeader: "flex items-center justify-between mb-10",
  sidebarLogo: "text-2xl font-serif font-bold tracking-tight",
  sidebarNav: "flex-1 space-y-1",
  navItem: "flex items-center space-x-3 px-4 py-3 rounded-xl transition-all duration-200 group text-on-primary/70 hover:text-on-primary hover:bg-primary-container",
  navItemActive: "bg-primary-container text-on-primary shadow-lg ring-1 ring-white/10",
  sidebarFooter: "mt-8 pt-8 border-t border-white/10",
  logoutBtn: "flex items-center space-x-3 px-4 py-3 rounded-xl text-on-primary/70 hover:text-on-primary hover:bg-destructive/10 transition-colors",
  adminMain: "flex-1 flex flex-col",
  adminHeader: "h-20 bg-surface flex items-center justify-between px-8 border-b border-outline-variant/30",
  mobileMenuBtn: "lg:hidden p-2 hover:bg-surface-container rounded-lg",
  userProfile: "flex items-center space-x-4 ml-auto",
  userBadge: "w-10 h-10 rounded-full bg-secondary-container flex items-center justify-center border-2 border-primary/10",
  pageContainer: "p-8 max-w-7xl mx-auto w-full",
};
