export const styles = {
  container: "min-h-screen bg-surface",
  main: "max-w-7xl mx-auto px-6 pt-24 pb-32",
  animatedSection: "animate-in fade-in slide-in-from-bottom duration-1000",
  filterBar: "flex flex-col lg:flex-row lg:items-center justify-between gap-8 mb-16 animate-in fade-in slide-in-from-bottom duration-1000 delay-200",
  searchWrapper: "flex-1 max-w-md relative group",
  searchIcon: "absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-muted-foreground group-focus-within:text-emerald-700 transition-colors",
  searchInput: "w-full bg-white border border-border/50 rounded-2xl py-3.5 pl-12 pr-6 outline-none focus:ring-2 focus:ring-emerald-500/10 focus:border-emerald-500/30 transition-all text-sm shadow-sm",
  blogGrid: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8 mb-16 animate-in fade-in slide-in-from-bottom duration-1000 delay-500",
  emptyState: "col-span-full py-20 text-center flex flex-col items-center",
  emptyIconBox: "w-16 h-16 bg-surface-container rounded-3xl flex items-center justify-center mb-6 border border-border/50",
  newsletterSection: "mt-32 p-12 lg:p-20 bg-emerald-950 rounded-3xl text-center relative overflow-hidden group",
  newsletterBgOrnament: "absolute top-0 right-0 w-96 h-96 bg-emerald-800/20 rounded-full blur-[100px] -mr-32 -mt-32 transition-transform duration-700 group-hover:scale-110",
  newsletterContent: "relative mx-auto max-w-2xl",
  newsletterTitle: "text-3xl font-serif text-emerald-50 mb-6 sm:text-4xl italic",
  newsletterDesc: "text-emerald-200/70 mb-10 text-lg leading-relaxed",
  formWrapper: "flex flex-col sm:flex-row gap-4 max-w-lg mx-auto",
  newsletterInput: "flex-1 px-6 py-4 rounded-xl bg-white/5 border border-white/10 text-white placeholder:text-emerald-100/30 outline-none focus:ring-2 focus:ring-emerald-500/50 transition-all",
  newsletterBtn: "px-8 py-4 bg-emerald-100 text-emerald-950 font-bold rounded-xl hover:bg-white transition-colors",
};
