export const styles = {
  container: "min-h-screen flex items-center justify-center relative overflow-hidden bg-surface",
  bgImage: "absolute inset-0 z-0 bg-cover bg-center transition-transform duration-1000 scale-105",
  bgOverlay: "absolute inset-0 z-1 bg-gradient-to-br from-primary/60 via-surface/30 to-secondary-container/20 backdrop-blur-[2px]",
  contentWrapper: "relative z-10 w-full max-w-lg px-6 animate-in fade-in slide-in-from-bottom-8 duration-1000",
  glassCard: "glassmorphism ghost-border rounded-[3rem] p-12 shadow-meditative overflow-hidden relative",
  starOverlay: "absolute inset-0 star-pattern opacity-10 pointer-events-none",
  header: "text-center mb-12",
  iconBox: "inline-flex items-center justify-center w-16 h-16 rounded-3xl bg-primary text-secondary-container mb-6 shadow-xl ring-8 ring-primary/5",
  title: "text-4xl font-serif font-bold text-primary mb-3",
  subtitle: "text-on-surface-variant font-medium",
  formGroup: "space-y-2",
  inputLabel: "text-sm font-bold text-primary/70 ml-1",
  inputWrapper: "relative group",
  inputIcon: "absolute left-4 top-1/2 -translate-y-1/2 text-primary/40 group-focus-within:text-primary transition-colors",
  formInput: "w-full bg-surface-container-low border border-outline-variant/30 rounded-2xl py-4 pl-12 pr-4 text-primary placeholder:text-primary/20 focus:outline-none focus:ring-4 focus:ring-primary/5 focus:border-primary transition-all font-medium",
  checkboxGroup: "flex items-start gap-3 px-1 py-2",
  checkboxInput: "mt-1 accent-primary rounded",
  checkboxLabel: "text-xs text-on-surface-variant leading-relaxed",
  submitButton: "w-full bg-primary text-on-primary py-5 rounded-2xl font-bold flex items-center justify-center space-x-3 hover:bg-primary-container shadow-xl shadow-primary/20 transform active:scale-95 transition-all disabled:opacity-70 group",
  footerDivider: "h-[1px] w-full bg-outline-variant/20 mb-8",
  footerText: "text-sm font-medium text-on-surface-variant",
};
