export const styles = {
  container: "min-h-screen flex items-center justify-center relative overflow-hidden bg-surface",
  bgImage: "absolute inset-0 z-0 bg-cover bg-center transition-transform duration-1000 scale-105",
  bgOverlay: "absolute inset-0 z-1 bg-gradient-to-tr from-primary/40 via-surface/40 to-transparent backdrop-blur-[2px]",
  ornamentNav: "absolute top-10 left-10 z-10 hidden lg:block",
  navLink: "flex items-center space-x-2 text-primary group",
  navIcon: "w-10 h-10 rounded-full border border-primary/20 flex items-center justify-center group-hover:bg-primary group-hover:text-on-primary transition-all",
  navTitle: "font-serif font-bold text-xl tracking-tight",
  contentWrapper: "relative z-10 w-full max-w-md px-6 animate-in fade-in zoom-in-95 duration-700",
  glassCard: "glassmorphism ghost-border rounded-[2.5rem] p-10 shadow-meditative overflow-hidden relative",
  starOverlay: "absolute inset-0 star-pattern opacity-10 pointer-events-none",
  header: "text-center mb-10",
  title: "text-4xl font-serif font-bold text-primary mb-3",
  subtitle: "text-on-surface-variant font-medium",
  formGroup: "space-y-2",
  inputLabel: "text-sm font-bold text-primary/70 ml-1",
  inputWrapper: "relative group",
  inputIcon: "absolute left-4 top-1/2 -translate-y-1/2 text-primary/40 group-focus-within:text-primary transition-colors",
  formInput: "w-full bg-surface-container-low border border-outline-variant/30 rounded-2xl py-4 pl-12 pr-4 text-primary placeholder:text-primary/20 focus:outline-none focus:ring-2 focus:ring-primary/10 focus:border-primary transition-all font-medium",
  forgotPassword: "text-xs font-bold text-primary hover:text-secondary-container transition-colors",
  submitButton: "w-full bg-primary text-on-primary py-5 rounded-2xl font-bold flex items-center justify-center space-x-3 hover:bg-primary-container shadow-lg shadow-primary/10 transform active:scale-95 transition-all disabled:opacity-70 group",
  dividerSection: "mt-10",
  dividerWrapper: "flex items-center gap-4 mb-8",
  dividerLine: "h-[1px] flex-1 bg-outline-variant/30",
  dividerText: "text-xs font-bold text-primary/30 uppercase tracking-widest",
  socialGrid: "grid grid-cols-2 gap-4",
  socialButton: "flex items-center justify-center gap-3 bg-surface-container-low border border-outline-variant/30 py-4 rounded-xl hover:bg-surface transition-colors",
  socialIconGoogle: "w-5 h-5 bg-[#4285F4] rounded-full",
  socialIconGithub: "w-5 h-5 bg-primary rounded-full",
  applyText: "text-center mt-8 text-sm font-medium text-primary/60",
};
