export const styles = {
  container: "space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-700",
  headerSection: "flex items-center justify-between",
  pageTitle: "text-3xl font-serif font-bold text-primary mb-2",
  pageSubtitle: "text-on-surface-variant font-medium",
  addButton: "bg-primary text-on-primary px-6 py-3 rounded-xl font-bold flex items-center gap-2 hover:bg-primary-container transition-all shadow-lg shadow-primary/10",
  tableContainer: "bg-surface-container-low border border-outline-variant/30 rounded-2xl overflow-hidden shadow-meditative",
  tableToolbar: "p-6 border-b border-outline-variant/20 flex items-center justify-between bg-surface/50",
  searchWrapper: "relative w-72",
  searchIcon: "absolute left-3 top-1/2 -translate-y-1/2 text-on-surface-variant",
  searchInput: "w-full bg-surface border border-outline-variant/20 rounded-lg py-2 pl-10 pr-4 text-sm focus:outline-none focus:border-primary transition-all",
  toolbarActions: "flex gap-2",
  actionLink: "text-sm font-bold text-primary px-4 py-2 hover:bg-primary/5 rounded-lg transition-colors",
  tableHead: "bg-surface-container/50",
  tableTh: "px-6 py-4 text-xs font-bold uppercase tracking-wider text-primary/60",
  tableRow: "hover:bg-surface/40 transition-colors group",
  tableTd: "px-6 py-5",
  duaInfoCell: "flex items-center gap-3",
  duaIconBox: "p-2 bg-primary/5 rounded-lg group-hover:bg-primary group-hover:text-on-primary transition-all",
  duaTitle: "font-bold text-primary",
  duaExcerpt: "text-xs text-on-surface-variant truncate max-w-[200px]",
  categoryBadge: "text-sm font-medium text-on-surface-variant bg-surface px-3 py-1 rounded-full border border-outline-variant/20",
  statusIndicator: "flex items-center gap-1.5",
  statusDot: "w-2 h-2 rounded-full",
  statusPublished: "bg-emerald-500",
  statusDraft: "bg-amber-500",
  actionsCell: "flex items-center justify-end gap-2",
  iconAction: "p-2 text-on-surface-variant hover:text-primary transition-colors",
  iconActionDelete: "p-2 text-on-surface-variant hover:text-destructive transition-colors",
  paginationSection: "flex items-center justify-between",
  paginationInfo: "text-sm text-on-surface-variant",
  paginationControls: "flex gap-2",
  pageBtn: "px-4 py-2 text-sm font-bold text-primary hover:bg-primary/5 rounded-lg transition-colors border border-outline-variant/20",
  pageBtnActive: "px-4 py-2 text-sm font-bold bg-primary text-on-primary rounded-lg transition-all shadow-md",
};
