export const styles = {
  container: "min-h-screen bg-surface selection:bg-secondary-container/30",
  main: "max-w-7xl mx-auto px-8 pt-12 pb-24",
  heroSection: "flex flex-col md:flex-row items-center justify-between mb-20 gap-12",
  heroTextBox: "max-w-xl space-y-6 text-center md:text-left",
  mainTitle: "text-6xl md:text-7xl font-serif",
  heroDesc: "text-lg text-on-surface-variant/80 leading-relaxed max-w-md",
  heroImageBox: "relative w-64 h-64 md:w-80 md:h-80",
  filterSection: "bg-surface-container-low/50 p-4 rounded-2xl mb-12 flex flex-col md:flex-row items-center gap-4",
  searchWrapper: "relative w-full md:w-96",
  searchInput: "pl-10 bg-surface-container/60 border-none rounded-xl",
  storiesGrid: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 items-stretch",
  featuredCard: "lg:col-span-2 lg:row-span-2 bg-[#003527] text-white overflow-hidden group hover:shadow-2xl transition-all duration-500 flex flex-col justify-end p-8 border-none relative star-pattern min-h-[550px]",
  featuredArabicTitle: "absolute top-8 right-8 text-[#fed65b] text-5xl opacity-40 group-hover:opacity-80 transition-opacity font-serif",
  prophetCard: "bg-surface shadow-[0_2px_15px_-3px_rgba(0,0,0,0.07),0_10px_20px_-2px_rgba(0,0,0,0.04)] hover:shadow-meditative transition-all duration-300 border border-outline-variant/10 p-6 flex flex-col justify-between group h-[320px]",
  prophetIconBox: "p-3 bg-surface-container-low rounded-xl text-primary group-hover:bg-primary group-hover:text-on-primary transition-colors duration-300",
  cardArabicName: "text-2xl font-serif text-on-surface-variant/20 italic group-hover:text-on-surface-variant/40 transition-colors",
  cardLink: "flex items-center space-x-2 text-[10px] font-bold uppercase tracking-widest text-primary/60 hover:text-primary transition-colors group/link mt-6",
  loadMoreBox: "mt-20 flex justify-center",
};
